flask_app/app/blueprints/__init__.py
from .home_page import home_page
from .upload_api import upload_api

flask_app/app/blueprints/home_page/__init__.py
from .blueprint import home_page

flask_app/app/blueprints/home_page/blueprint.py
from flask import Blueprint, render_template, request

home_page = Blueprint('home_page', __name__)
@home_page.route('/')
def index():
    return render_template('home_page.html') 

flask_app/app/blueprints/upload_api/__init__.py
from .blueprint import upload_api

flask_app/app/blueprints/upload_api/blueprint.py
from flask import Blueprint, render_template, request
import tensorflow as tf
import re
import base64
import numpy as np 
import os
from werkzeug.utils import secure_filename


def parse_image(imgData):
    img_str = re.search(b"base64,(.*)", imgData).group(1)
    img_decode = base64.decodebytes(img_str)
    with open('output.png', "wb") as f:
        f.write(img_decode)
    return img_decode

model = tf.keras.models.load_model('models/nhan_catmodel.h5')

upload_api = Blueprint('upload_api', __name__)

flask_app/app/main.py
from blueprints import home_page
from flask import Flask, Blueprint, render_template, request
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import re
import base64
import numpy as np 
import os
from werkzeug.utils import secure_filename
import sql 

app = Flask(__name__)
app.register_blueprint(home_page)
app.config['UPLOAD_FOLDER'] = os.getcwd() + '/static/images/'

model = tf.keras.models.load_model('/Users/nhanpham/CoderSchool/week6/flask_app/app/models/nhan_catmodel.h5')

def parse_img(path):
    image = path
    image = load_img(image)
    image = img_to_array(image)
    image = tf.image.resize(image, [150,150])
    image /= 255.0
    image = np.expand_dims(image, 0)
    return image

@app.route('/upload', methods = ['GET', 'POST'])
def upload():
    if request.method == 'POST':
        try:
            f = request.files['file']
            if f:
                path = os.path.join(app.config['UPLOAD_FOLDER'], f.filename)
                f.save(path)
                image = parse_img(path)
                prediction = model.predict(image)
                if prediction[0][0] < 0.5:
                    prediction = 'cat'
                else:
                    prediction = 'dog'
                return render_template('predict.html', path = f.filename, predict = prediction)        
        except:
            data = request.json
            label = data.split()[0]
            img = data.split()[1]
            
            label = {'cat': 0, 'dog':1}.get(label)
            path = os.path.join(app.config['UPLOAD_FOLDER'], img)
            
            sql.create_table()
            sql.save_into_db(path, label)
            os.remove(path)
            return render_template('predict.html', path = "#", predict = "")


if __name__ == '__main__':
  app.run(host='127.0.0.1', port=8000, debug=True)
 

flask_app/app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>CatOrDog</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="static/css/style.css" rel="stylesheet">
</head>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <div class="container">
            <a class="navbar-brand" href="{{url_for('home_page.index')}}">CAT OR DOG?</a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                <a class="nav-link" href="https://github.com/nhanphan0411">Find me on GitHub
                    <span class="sr-only">(current)</span>
                </a>
                </li>
            </ul>
            </div>
        </div>
    </nav>

<body class="text-center">
      
    {% block content%} {% endblock %}

    <script src="static/js/jquery-3.4.1.min.js"></script>
    <script src="static/js/index.js"></script>
    
    <!-- AJAX optional Get Image-->
    <!-- <script type="text/javascript">
        $("#myButton").click(function(){
            $('#result').text('  Predicting...');
            var $SCRIPT_ROOT = {{request.script_root|tojson|safe}};
            var canvasObj = document.getElementById("myImg");
            var img = canvasObj.toDataURL('image/jpeg');
            $.ajax({
                type: "POST",
                url: $SCRIPT_ROOT + "/upload/",
                data: img,
                success: function(data){
                    $('#result').text('Predictions ' + data);
                }
            });
        });
    </script> -->
    
    <!-- UPLOAD PHOTO -->
    <script type="text/javascript">
        /* The uploader form */
        $(function () {
            $(":file").change(function () {
                if (this.files && this.files[0]) {
                    var reader = new FileReader();
    
                    reader.onload = imageIsLoaded;
                    reader.readAsDataURL(this.files[0]);
                }
            });
        });
    
        function imageIsLoaded(e) {
            $('#myImg').attr('src', e.target.result);
            $('#yourImage').attr('src', e.target.result);
        };

    </script>

    <!-- AJAX optional WrongFeedback-->
    <script type="text/javascript">
        $("#myFeedbackButton").click(function(){
            
            var $SCRIPT_ROOT = {{request.script_root|tojson|safe}};
            var predict = document.getElementById('result').textContent.split(" ").slice(-2)[0];
            var img = document.getElementById('blah').src.split("/").pop()
            var datastr = predict + " " + img
            $.ajax({
                type: "POST",
                url: $SCRIPT_ROOT + "/upload",
                contentType: "application/json",
                data: JSON.stringify(datastr),
                success: function(){
                    $('#result').text('Thank you for your feedback!');
                }
            });
        });
    </script>

    <!-- TrueFeedback -->
        <script type="text/javascript">
            $("#TrueButton").click(function(){
                $('#result').text('YAY!');
            });
        </script>
    </body>

<!-- Footer -->
  <footer id="sticky-footer" class="py-4 bg-dark text-white-50">
        <div class="container text-center">
        <small>Copyright &copy; Mariana 2019</small>
        </div>
    </footer>

</html>

flask_app/app/templates/home_page.html
{% extends "base.html" %}
{% block content %}

<!-- Content -->
<div class="container-fluid">
    <div class="row no-gutter">
        <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
          <div class="col-md-8 col-lg-6">
            <div class="login d-flex align-items-center py-5">
              <div class="container">
                <div class="row">
                  <div class="col-md-9 col-lg-8 mx-auto">
                    <h3 class="login-heading mb-4">Input your photo!</h3>
                    <form action = "/upload" method = "POST" enctype = "multipart/form-data">
                        <div class="form-label-group">
                            <img id="blah" name='img' src="#" alt="your image" style = "display:none"/>
                            <div class="input-group">
                                    <div class="custom-file">
                                        <input type='file' class="custom-file-input" id="inputGroupFile01" name = 'file' onchange="readURL(this);"/>
                                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                                    </div>
                                    <div class="input-group-append">
                                        <input id="myButton" class="btn btn-secondary" type = "submit" value="Predict"/>
                                    </div>
                                </div>
                            <div class="container text-center my-auto">
                                <br><h2 class="h3 mb-3 font-weight-normal" id="result" style = "display:none">Predictions</h2>
                            </div>
                        </div>    
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

{% endblock %}

flask_app/app/templates/predict.html
{% extends "base.html" %}
{% block content %}

<!-- Content -->
<div class="container-fluid">
    <div class="row no-gutter">
        <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
          <div class="col-md-8 col-lg-6">
            <div class="login d-flex align-items-center py-5">
              <div class="container">
                <div class="row">
                  <div class="col-md-9 col-lg-8 mx-auto">
                    <h3 class="login-heading mb-4" id="result">Trust me, it's a {{predict}} !</h3>
                    
                    <div class="form-label-group">
                            <img id="blah" name='img' src="static/images/{{path}}" alt="your image" width = '300'/>
                        </div>
                    
                    <div class="form-label-group">
                            <button type="button" id="TrueButton" class="btn btn-outline-warning btn-sm">Correct</button>
                            <input id="myFeedbackButton" class="btn btn-outline-info btn-sm" type = "submit" value="Something Wrong"/>
                        </div>        

                    <div class="form-label-group">
                            <a class="btn btn-secondary" href="{{url_for('home_page.index')}}">Back to home</a>
                            </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


    <!-- <div class="masthead d-flex">
            <div class="container text-center my-auto">
                <h1 class="h3 mb-3 font-weight-normal" id="result">Predictions:</h1>
                <form action = "/upload" method = "POST" enctype = "multipart/form-data">
                    <img id="blah" class ="center" name='img' src="#" alt="your image"/>
                    <br><input type='file' name = 'file' onchange="readURL(this);" />   
                    <input id="myButton" class="btn btn-xl btn-dark" type = "submit" value="Predict"/>
                </form>
            </div>
            <div class="overlay"></div>
        </div> -->

{% endblock %}

flask_app/app/templates/upload_api.html
{% extends "base.html" %}
{% block content %}
<!-- Your code here -->
{% endblock %}